DROP TABLE
IF EXISTS `t_user`;

CREATE TABLE `t_user` (
	`USER_ID` INT (11) NOT NULL AUTO_INCREMENT,
	`USER_NAME` CHAR (30) NOT NULL,
	`USER_PASSWORD` CHAR (10) NOT NULL,
	PRIMARY KEY (`USER_ID`),
	KEY `IDX_NAME` (`USER_NAME`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8;

INSERT INTO `t_user` (USER_ID, USER_NAME, USER_PASSWORD) VALUES (1, 'Andy Budd', '123456');
INSERT INTO `t_user` (USER_ID, USER_NAME, USER_PASSWORD) VALUES (2, 'Jeremy Keith', '654321');
